#!/bin/bash
#
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#
#PBS -q hyper
#
#PBS -M egentry@ucsc.edu
#PBS -m e
#
#PBS -e ./ICs/double/
#PBS -o ./ICs/double/
#
#PBS -S /bin/bash
#
cd $PBS_O_WORKDIR

source $HOME/.bashrc
export LD_LIBRARY_PATH="grackle/local/lib:$LD_LIBRARY_PATH"
time mpirun -np 16 ./ICs/double/GIZMO ICs/double/double.params
