#!/bin/bash
#
#PBS -l nodes=2:ppn=16
#PBS -l walltime=48:00:00
#
#PBS -q normal
#
#PBS -M egentry@ucsc.edu
#PBS -m e
#
#PBS -e ./runs/cluster_cooling_200/inputs/
#PBS -o ./runs/cluster_cooling_200/inputs/
#
#PBS -S /bin/bash
#
cd $PBS_O_WORKDIR

source $HOME/.bashrc
export LD_LIBRARY_PATH="grackle/local/lib:$LD_LIBRARY_PATH"
time mpirun -np 32 ./runs/cluster_cooling_200/inputs/GIZMO runs/cluster_cooling_200/inputs/cluster_cooling_200.params
