#!/bin/bash
#
#PBS -l nodes=2:ppn=16
#PBS -l walltime=48:00:00
#
#PBS -q normal
#
#PBS -M egentry@ucsc.edu
#PBS -m e
#
#PBS -e ./ICs/cluster_cooling_300/
#PBS -o ./ICs/cluster_cooling_300/
#
#PBS -S /bin/bash
#
cd $PBS_O_WORKDIR

# test if RESTART_TYPE was passed to qsub
# (RESTART_TYPE=2 for restarting from checkpoint files; RESTART_TYPE=1 for restarting from restart files)
x="asdf"
if [ -z ${RESTART_TYPE+x} ]; 
	then RESTART_TYPE=2; # default, if RESTART_TYPE not set
fi

source $HOME/.bashrc
export LD_LIBRARY_PATH="grackle/local/lib:$LD_LIBRARY_PATH"
time mpirun -np 32 ./ICs/cluster_cooling_300/GIZMO ICs/cluster_cooling_300/cluster_cooling_300.params.restart $RESTART_TYPE
