#!/bin/bash
#
#PBS -l nodes=2:ppn=16
#PBS -l walltime=48:00:00
#
#PBS -q normal
#
#PBS -M egentry@ucsc.edu
#PBS -m e
#
#PBS -e ./ICs/cluster_cooling_300/
#PBS -o ./ICs/cluster_cooling_300/
#
#PBS -S /bin/bash
#
cd $PBS_O_WORKDIR

source $HOME/.bashrc
export LD_LIBRARY_PATH="grackle/local/lib:$LD_LIBRARY_PATH"
time mpirun -np 32 ./ICs/cluster_cooling_300/GIZMO ICs/cluster_cooling_300/cluster_cooling_300.params 1
