#!/bin/bash
#
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#
#PBS -q hyper
#
#PBS -M egentry@ucsc.edu
#PBS -m e
#
#PBS -e ./runs/single_cooling/inputs/
#PBS -o ./runs/single_cooling/inputs/
#
#PBS -S /bin/bash
#
cd $PBS_O_WORKDIR

source $HOME/.bashrc
export LD_LIBRARY_PATH="grackle/local/lib:$LD_LIBRARY_PATH"
time mpirun -np 16 ./runs/single_cooling/inputs/GIZMO runs/single_cooling/inputs/single_cooling.params
