#!/bin/bash

RUN_NAME=$1

echo cleaning: $RUN_NAME

rm -f ICs/$RUN_NAME/*-usedvalues
rm -f ICs/$RUN_NAME/*test.*
rm -f output/$RUN_NAME/snapshot_*.hdf5
rm -rf output/$RUN_NAME/restartfiles
rm -f output/$RUN_NAME/balance.txt
rm -f output/$RUN_NAME/cpu.txt
rm -f output/$RUN_NAME/info.txt
rm -f output/$RUN_NAME/parameters-usedvalues
rm -f output/$RUN_NAME/timebin.txt
rm -f output/$RUN_NAME/timings.txt
rm -f output/$RUN_NAME/energy.txt
