#!/bin/bash

RUN_NAME=$1

echo cleaning: $RUN_NAME

rm -f  runs/$RUN_NAME/inputs/*-usedvalues
rm -f  runs/$RUN_NAME/inputs/*test.*
rm -f  runs/$RUN_NAME/inputs/RESTART
rm -f  runs/$RUN_NAME/inputs/end
rm -f  runs/$RUN_NAME/outputs/snapshot_*.hdf5
rm -rf runs/$RUN_NAME/outputs/restartfiles
rm -f  runs/$RUN_NAME/outputs/balance.txt
rm -f  runs/$RUN_NAME/outputs/cpu.txt
rm -f  runs/$RUN_NAME/outputs/info.txt
rm -f  runs/$RUN_NAME/outputs/parameters-usedvalues
rm -f  runs/$RUN_NAME/outputs/timebin.txt
rm -f  runs/$RUN_NAME/outputs/timings.txt
rm -f  runs/$RUN_NAME/outputs/energy.txt
