#!/bin/bash
#
#PBS -l nodes=4:ppn=16
#PBS -l walltime=48:00:00
#
#PBS -q normal
#
#PBS -M egentry@ucsc.edu
#PBS -m e
#
#PBS -e ./ICs/cluster/
#PBS -o ./ICs/cluster/
#
#PBS -S /bin/bash
#
cd $PBS_O_WORKDIR

source $HOME/.bashrc
export LD_LIBRARY_PATH="grackle/local/lib:$LD_LIBRARY_PATH"
time mpirun -np 64 ./ICs/cluster/GIZMO ICs/cluster/cluster.params
